spring:
  config:
    import: optional:application-local.yaml

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=PublicationTracker;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587

server:
  port: 8080